/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.pstn.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * V1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner {
    @JsonProperty(value = "area")
    private Long area;

    @JsonProperty(value = "error_msg")
    private String errorMsg;

    @JsonProperty(value = "extension_number")
    private String extensionNumber;

    @JsonProperty(value = "phone")
    private String phone;

    /**
     */
    public V1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner() {
    }

    /**
     * @param area 国家/地区代码。（例如：中国是86）
     */
    public V1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner area(Long area) {
        this.area = area;
        return this;
    }
    /**
     * @return area 国家/地区代码。（例如：中国是86）
     **/
    public Long getArea() {
        return area;
    }

    /**
     * @param area 国家/地区代码。（例如：中国是86）
     */
    public void setArea(Long area) {
        this.area = area;
    }
    /**
     * @param errorMsg 错误信息
     */
    public V1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner errorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
        return this;
    }
    /**
     * @return errorMsg 错误信息
     **/
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * @param errorMsg 错误信息
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
    }
    /**
     * @param extensionNumber 固定电话分机号。
     */
    public V1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner extensionNumber(String extensionNumber) {
        this.extensionNumber = extensionNumber;
        return this;
    }
    /**
     * @return extensionNumber 固定电话分机号。
     **/
    public String getExtensionNumber() {
        return extensionNumber;
    }

    /**
     * @param extensionNumber 固定电话分机号。
     */
    public void setExtensionNumber(String extensionNumber) {
        this.extensionNumber = extensionNumber;
    }
    /**
     * @param phone 电话号码或固定电话总机号。
     */
    public V1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner phone(String phone) {
        this.phone = phone;
        return this;
    }
    /**
     * @return phone 电话号码或固定电话总机号。
     **/
    public String getPhone() {
        return phone;
    }

    /**
     * @param phone 电话号码或固定电话总机号。
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner v1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner = (V1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner) o;
        return Objects.equals(this.area, v1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner.area) &&
            Objects.equals(this.errorMsg, v1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner.errorMsg) &&
            Objects.equals(this.extensionNumber, v1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner.extensionNumber) &&
            Objects.equals(this.phone, v1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner.phone);
    }

    @Override
    public int hashCode() {
        return Objects.hash(area, errorMsg, extensionNumber, phone);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner {\n");
        sb.append("    area: ").append(toIndentedString(area)).append("\n");
        sb.append("    errorMsg: ").append(toIndentedString(errorMsg)).append("\n");
        sb.append("    extensionNumber: ").append(toIndentedString(extensionNumber)).append("\n");
        sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

