/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.pstn.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * V1MeetingMeetingIdPhoneCalloutPost200Response
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1MeetingMeetingIdPhoneCalloutPost200Response {
    @JsonProperty(value = "invalid_phone_numbers")
    private List<V1MeetingMeetingIdPhoneCalloutPost200ResponseInvalidPhoneNumbersInner> invalidPhoneNumbers;

    @JsonProperty(value = "meeting_id")
    private String meetingId;

    @JsonProperty(value = "phone_numbers")
    private List<V1MeetingMeetingIdPhoneCalloutPost200ResponsePhoneNumbersInner> phoneNumbers;

    /**
     */
    public V1MeetingMeetingIdPhoneCalloutPost200Response() {
    }

    /**
     * @param invalidPhoneNumbers 外呼的电话号码对象列表。
     */
    public V1MeetingMeetingIdPhoneCalloutPost200Response invalidPhoneNumbers(List<V1MeetingMeetingIdPhoneCalloutPost200ResponseInvalidPhoneNumbersInner> invalidPhoneNumbers) {
        this.invalidPhoneNumbers = invalidPhoneNumbers;
        return this;
    }
    /**
     * @return invalidPhoneNumbers 外呼的电话号码对象列表。
     **/
    public List<V1MeetingMeetingIdPhoneCalloutPost200ResponseInvalidPhoneNumbersInner> getInvalidPhoneNumbers() {
        return invalidPhoneNumbers;
    }

    /**
     * @param invalidPhoneNumbers 外呼的电话号码对象列表。
     */
    public void setInvalidPhoneNumbers(List<V1MeetingMeetingIdPhoneCalloutPost200ResponseInvalidPhoneNumbersInner> invalidPhoneNumbers) {
        this.invalidPhoneNumbers = invalidPhoneNumbers;
    }
    /**
     * @param meetingId 会议的唯一ID
     */
    public V1MeetingMeetingIdPhoneCalloutPost200Response meetingId(String meetingId) {
        this.meetingId = meetingId;
        return this;
    }
    /**
     * @return meetingId 会议的唯一ID
     **/
    public String getMeetingId() {
        return meetingId;
    }

    /**
     * @param meetingId 会议的唯一ID
     */
    public void setMeetingId(String meetingId) {
        this.meetingId = meetingId;
    }
    /**
     * @param phoneNumbers 外呼的电话号码对象列表。
     */
    public V1MeetingMeetingIdPhoneCalloutPost200Response phoneNumbers(List<V1MeetingMeetingIdPhoneCalloutPost200ResponsePhoneNumbersInner> phoneNumbers) {
        this.phoneNumbers = phoneNumbers;
        return this;
    }
    /**
     * @return phoneNumbers 外呼的电话号码对象列表。
     **/
    public List<V1MeetingMeetingIdPhoneCalloutPost200ResponsePhoneNumbersInner> getPhoneNumbers() {
        return phoneNumbers;
    }

    /**
     * @param phoneNumbers 外呼的电话号码对象列表。
     */
    public void setPhoneNumbers(List<V1MeetingMeetingIdPhoneCalloutPost200ResponsePhoneNumbersInner> phoneNumbers) {
        this.phoneNumbers = phoneNumbers;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1MeetingMeetingIdPhoneCalloutPost200Response v1MeetingMeetingIdPhoneCalloutPost200Response = (V1MeetingMeetingIdPhoneCalloutPost200Response) o;
        return Objects.equals(this.invalidPhoneNumbers, v1MeetingMeetingIdPhoneCalloutPost200Response.invalidPhoneNumbers) &&
            Objects.equals(this.meetingId, v1MeetingMeetingIdPhoneCalloutPost200Response.meetingId) &&
            Objects.equals(this.phoneNumbers, v1MeetingMeetingIdPhoneCalloutPost200Response.phoneNumbers);
    }

    @Override
    public int hashCode() {
        return Objects.hash(invalidPhoneNumbers, meetingId, phoneNumbers);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1MeetingMeetingIdPhoneCalloutPost200Response {\n");
        sb.append("    invalidPhoneNumbers: ").append(toIndentedString(invalidPhoneNumbers)).append("\n");
        sb.append("    meetingId: ").append(toIndentedString(meetingId)).append("\n");
        sb.append("    phoneNumbers: ").append(toIndentedString(phoneNumbers)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

