/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.pstn.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * V1MeetingMeetingIdPhoneCancelcallPost200Response
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1MeetingMeetingIdPhoneCancelcallPost200Response {
    @JsonProperty(value = "failed_list")
    private List<V1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner> failedList;

    @JsonProperty(value = "success_list")
    private List<V1MeetingMeetingIdPhoneCancelcallPost200ResponseSuccessListInner> successList;

    /**
     */
    public V1MeetingMeetingIdPhoneCancelcallPost200Response() {
    }

    /**
     * @param failedList 取消呼叫失败的列表
     */
    public V1MeetingMeetingIdPhoneCancelcallPost200Response failedList(List<V1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner> failedList) {
        this.failedList = failedList;
        return this;
    }
    /**
     * @return failedList 取消呼叫失败的列表
     **/
    public List<V1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner> getFailedList() {
        return failedList;
    }

    /**
     * @param failedList 取消呼叫失败的列表
     */
    public void setFailedList(List<V1MeetingMeetingIdPhoneCancelcallPost200ResponseFailedListInner> failedList) {
        this.failedList = failedList;
    }
    /**
     * @param successList 取消呼叫成功的列表
     */
    public V1MeetingMeetingIdPhoneCancelcallPost200Response successList(List<V1MeetingMeetingIdPhoneCancelcallPost200ResponseSuccessListInner> successList) {
        this.successList = successList;
        return this;
    }
    /**
     * @return successList 取消呼叫成功的列表
     **/
    public List<V1MeetingMeetingIdPhoneCancelcallPost200ResponseSuccessListInner> getSuccessList() {
        return successList;
    }

    /**
     * @param successList 取消呼叫成功的列表
     */
    public void setSuccessList(List<V1MeetingMeetingIdPhoneCancelcallPost200ResponseSuccessListInner> successList) {
        this.successList = successList;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1MeetingMeetingIdPhoneCancelcallPost200Response v1MeetingMeetingIdPhoneCancelcallPost200Response = (V1MeetingMeetingIdPhoneCancelcallPost200Response) o;
        return Objects.equals(this.failedList, v1MeetingMeetingIdPhoneCancelcallPost200Response.failedList) &&
            Objects.equals(this.successList, v1MeetingMeetingIdPhoneCancelcallPost200Response.successList);
    }

    @Override
    public int hashCode() {
        return Objects.hash(failedList, successList);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1MeetingMeetingIdPhoneCancelcallPost200Response {\n");
        sb.append("    failedList: ").append(toIndentedString(failedList)).append("\n");
        sb.append("    successList: ").append(toIndentedString(successList)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

