/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.meetings.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * V1MeetingsGet200ResponseMeetingInfoListInnerGuestsInner
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1MeetingsGet200ResponseMeetingInfoListInnerGuestsInner {
    @JsonProperty(value = "area")
    private String area;

    @JsonProperty(value = "guest_name")
    private String guestName;

    @JsonProperty(value = "phone_number")
    private String phoneNumber;

    /**
     */
    public V1MeetingsGet200ResponseMeetingInfoListInnerGuestsInner() {
    }

    /**
     * @param area 
     */
    public V1MeetingsGet200ResponseMeetingInfoListInnerGuestsInner area(String area) {
        this.area = area;
        return this;
    }
    /**
     * @return area 
     **/
    public String getArea() {
        return area;
    }

    /**
     * @param area 
     */
    public void setArea(String area) {
        this.area = area;
    }
    /**
     * @param guestName 
     */
    public V1MeetingsGet200ResponseMeetingInfoListInnerGuestsInner guestName(String guestName) {
        this.guestName = guestName;
        return this;
    }
    /**
     * @return guestName 
     **/
    public String getGuestName() {
        return guestName;
    }

    /**
     * @param guestName 
     */
    public void setGuestName(String guestName) {
        this.guestName = guestName;
    }
    /**
     * @param phoneNumber 
     */
    public V1MeetingsGet200ResponseMeetingInfoListInnerGuestsInner phoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
        return this;
    }
    /**
     * @return phoneNumber 
     **/
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * @param phoneNumber 
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1MeetingsGet200ResponseMeetingInfoListInnerGuestsInner v1MeetingsGet200ResponseMeetingInfoListInnerGuestsInner = (V1MeetingsGet200ResponseMeetingInfoListInnerGuestsInner) o;
        return Objects.equals(this.area, v1MeetingsGet200ResponseMeetingInfoListInnerGuestsInner.area) &&
            Objects.equals(this.guestName, v1MeetingsGet200ResponseMeetingInfoListInnerGuestsInner.guestName) &&
            Objects.equals(this.phoneNumber, v1MeetingsGet200ResponseMeetingInfoListInnerGuestsInner.phoneNumber);
    }

    @Override
    public int hashCode() {
        return Objects.hash(area, guestName, phoneNumber);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1MeetingsGet200ResponseMeetingInfoListInnerGuestsInner {\n");
        sb.append("    area: ").append(toIndentedString(area)).append("\n");
        sb.append("    guestName: ").append(toIndentedString(guestName)).append("\n");
        sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

