/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.meetings.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * 视频
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInnerVideo {
    @JsonProperty(value = "downstream_bitrate")
    private String downstreamBitrate;

    @JsonProperty(value = "downstream_framerate")
    private String downstreamFramerate;

    @JsonProperty(value = "downstream_resolution")
    private String downstreamResolution;

    @JsonProperty(value = "upstream_bitrate")
    private String upstreamBitrate;

    @JsonProperty(value = "upstream_framerate")
    private String upstreamFramerate;

    @JsonProperty(value = "upstream_resolution")
    private String upstreamResolution;

    /**
     */
    public V1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInnerVideo() {
    }

    /**
     * @param downstreamBitrate 下行码率（kbps）
     */
    public V1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInnerVideo downstreamBitrate(String downstreamBitrate) {
        this.downstreamBitrate = downstreamBitrate;
        return this;
    }
    /**
     * @return downstreamBitrate 下行码率（kbps）
     **/
    public String getDownstreamBitrate() {
        return downstreamBitrate;
    }

    /**
     * @param downstreamBitrate 下行码率（kbps）
     */
    public void setDownstreamBitrate(String downstreamBitrate) {
        this.downstreamBitrate = downstreamBitrate;
    }
    /**
     * @param downstreamFramerate 下行帧率（fps）
     */
    public V1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInnerVideo downstreamFramerate(String downstreamFramerate) {
        this.downstreamFramerate = downstreamFramerate;
        return this;
    }
    /**
     * @return downstreamFramerate 下行帧率（fps）
     **/
    public String getDownstreamFramerate() {
        return downstreamFramerate;
    }

    /**
     * @param downstreamFramerate 下行帧率（fps）
     */
    public void setDownstreamFramerate(String downstreamFramerate) {
        this.downstreamFramerate = downstreamFramerate;
    }
    /**
     * @param downstreamResolution 下行分辨率
     */
    public V1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInnerVideo downstreamResolution(String downstreamResolution) {
        this.downstreamResolution = downstreamResolution;
        return this;
    }
    /**
     * @return downstreamResolution 下行分辨率
     **/
    public String getDownstreamResolution() {
        return downstreamResolution;
    }

    /**
     * @param downstreamResolution 下行分辨率
     */
    public void setDownstreamResolution(String downstreamResolution) {
        this.downstreamResolution = downstreamResolution;
    }
    /**
     * @param upstreamBitrate 上行码率（kbps）
     */
    public V1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInnerVideo upstreamBitrate(String upstreamBitrate) {
        this.upstreamBitrate = upstreamBitrate;
        return this;
    }
    /**
     * @return upstreamBitrate 上行码率（kbps）
     **/
    public String getUpstreamBitrate() {
        return upstreamBitrate;
    }

    /**
     * @param upstreamBitrate 上行码率（kbps）
     */
    public void setUpstreamBitrate(String upstreamBitrate) {
        this.upstreamBitrate = upstreamBitrate;
    }
    /**
     * @param upstreamFramerate 上行帧率（fps）
     */
    public V1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInnerVideo upstreamFramerate(String upstreamFramerate) {
        this.upstreamFramerate = upstreamFramerate;
        return this;
    }
    /**
     * @return upstreamFramerate 上行帧率（fps）
     **/
    public String getUpstreamFramerate() {
        return upstreamFramerate;
    }

    /**
     * @param upstreamFramerate 上行帧率（fps）
     */
    public void setUpstreamFramerate(String upstreamFramerate) {
        this.upstreamFramerate = upstreamFramerate;
    }
    /**
     * @param upstreamResolution 上行分辨率
     */
    public V1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInnerVideo upstreamResolution(String upstreamResolution) {
        this.upstreamResolution = upstreamResolution;
        return this;
    }
    /**
     * @return upstreamResolution 上行分辨率
     **/
    public String getUpstreamResolution() {
        return upstreamResolution;
    }

    /**
     * @param upstreamResolution 上行分辨率
     */
    public void setUpstreamResolution(String upstreamResolution) {
        this.upstreamResolution = upstreamResolution;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInnerVideo v1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInnerVideo = (V1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInnerVideo) o;
        return Objects.equals(this.downstreamBitrate, v1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInnerVideo.downstreamBitrate) &&
            Objects.equals(this.downstreamFramerate, v1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInnerVideo.downstreamFramerate) &&
            Objects.equals(this.downstreamResolution, v1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInnerVideo.downstreamResolution) &&
            Objects.equals(this.upstreamBitrate, v1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInnerVideo.upstreamBitrate) &&
            Objects.equals(this.upstreamFramerate, v1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInnerVideo.upstreamFramerate) &&
            Objects.equals(this.upstreamResolution, v1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInnerVideo.upstreamResolution);
    }

    @Override
    public int hashCode() {
        return Objects.hash(downstreamBitrate, downstreamFramerate, downstreamResolution, upstreamBitrate, upstreamFramerate, upstreamResolution);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInnerVideo {\n");
        sb.append("    downstreamBitrate: ").append(toIndentedString(downstreamBitrate)).append("\n");
        sb.append("    downstreamFramerate: ").append(toIndentedString(downstreamFramerate)).append("\n");
        sb.append("    downstreamResolution: ").append(toIndentedString(downstreamResolution)).append("\n");
        sb.append("    upstreamBitrate: ").append(toIndentedString(upstreamBitrate)).append("\n");
        sb.append("    upstreamFramerate: ").append(toIndentedString(upstreamFramerate)).append("\n");
        sb.append("    upstreamResolution: ").append(toIndentedString(upstreamResolution)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

