/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.meetings.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * V1MeetingsMeetingIdEnrollIdsPost200Response
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1MeetingsMeetingIdEnrollIdsPost200Response {
    @JsonProperty(value = "enroll_id_list")
    private List<V1MeetingsMeetingIdEnrollIdsPost200ResponseEnrollIdListInner> enrollIdList;

    @JsonProperty(value = "meeting_id")
    private String meetingId;

    /**
     */
    public V1MeetingsMeetingIdEnrollIdsPost200Response() {
    }

    /**
     * @param enrollIdList 成员报名 ID 数组，仅返回已报名成员的报名 ID，若传入的用户无人报名，则无该字段。
     */
    public V1MeetingsMeetingIdEnrollIdsPost200Response enrollIdList(List<V1MeetingsMeetingIdEnrollIdsPost200ResponseEnrollIdListInner> enrollIdList) {
        this.enrollIdList = enrollIdList;
        return this;
    }
    /**
     * @return enrollIdList 成员报名 ID 数组，仅返回已报名成员的报名 ID，若传入的用户无人报名，则无该字段。
     **/
    public List<V1MeetingsMeetingIdEnrollIdsPost200ResponseEnrollIdListInner> getEnrollIdList() {
        return enrollIdList;
    }

    /**
     * @param enrollIdList 成员报名 ID 数组，仅返回已报名成员的报名 ID，若传入的用户无人报名，则无该字段。
     */
    public void setEnrollIdList(List<V1MeetingsMeetingIdEnrollIdsPost200ResponseEnrollIdListInner> enrollIdList) {
        this.enrollIdList = enrollIdList;
    }
    /**
     * @param meetingId 会议ID
     */
    public V1MeetingsMeetingIdEnrollIdsPost200Response meetingId(String meetingId) {
        this.meetingId = meetingId;
        return this;
    }
    /**
     * @return meetingId 会议ID
     **/
    public String getMeetingId() {
        return meetingId;
    }

    /**
     * @param meetingId 会议ID
     */
    public void setMeetingId(String meetingId) {
        this.meetingId = meetingId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1MeetingsMeetingIdEnrollIdsPost200Response v1MeetingsMeetingIdEnrollIdsPost200Response = (V1MeetingsMeetingIdEnrollIdsPost200Response) o;
        return Objects.equals(this.enrollIdList, v1MeetingsMeetingIdEnrollIdsPost200Response.enrollIdList) &&
            Objects.equals(this.meetingId, v1MeetingsMeetingIdEnrollIdsPost200Response.meetingId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(enrollIdList, meetingId);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1MeetingsMeetingIdEnrollIdsPost200Response {\n");
        sb.append("    enrollIdList: ").append(toIndentedString(enrollIdList)).append("\n");
        sb.append("    meetingId: ").append(toIndentedString(meetingId)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

