/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.meetings.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * V1MeetingsMeetingIdEnrollUnregistrationDelete200Response
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1MeetingsMeetingIdEnrollUnregistrationDelete200Response {
    @JsonProperty(value = "total_count")
    private Long totalCount;

    /**
     */
    public V1MeetingsMeetingIdEnrollUnregistrationDelete200Response() {
    }

    /**
     * @param totalCount 成功删除的报名信息数量
     */
    public V1MeetingsMeetingIdEnrollUnregistrationDelete200Response totalCount(Long totalCount) {
        this.totalCount = totalCount;
        return this;
    }
    /**
     * @return totalCount 成功删除的报名信息数量
     **/
    public Long getTotalCount() {
        return totalCount;
    }

    /**
     * @param totalCount 成功删除的报名信息数量
     */
    public void setTotalCount(Long totalCount) {
        this.totalCount = totalCount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1MeetingsMeetingIdEnrollUnregistrationDelete200Response v1MeetingsMeetingIdEnrollUnregistrationDelete200Response = (V1MeetingsMeetingIdEnrollUnregistrationDelete200Response) o;
        return Objects.equals(this.totalCount, v1MeetingsMeetingIdEnrollUnregistrationDelete200Response.totalCount);
    }

    @Override
    public int hashCode() {
        return Objects.hash(totalCount);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1MeetingsMeetingIdEnrollUnregistrationDelete200Response {\n");
        sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

