/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.meetings.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * V1MeetingsMeetingIdQosGet200ResponseParticipantsInner
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1MeetingsMeetingIdQosGet200ResponseParticipantsInner {
    @JsonProperty(value = "ms_open_id")
    private String msOpenId;

    @JsonProperty(value = "nick_name")
    private String nickName;

    @JsonProperty(value = "qos_details")
    private List<V1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInner> qosDetails;

    /**
     */
    public V1MeetingsMeetingIdQosGet200ResponseParticipantsInner() {
    }

    /**
     * @param msOpenId 会中ID
     */
    public V1MeetingsMeetingIdQosGet200ResponseParticipantsInner msOpenId(String msOpenId) {
        this.msOpenId = msOpenId;
        return this;
    }
    /**
     * @return msOpenId 会中ID
     **/
    public String getMsOpenId() {
        return msOpenId;
    }

    /**
     * @param msOpenId 会中ID
     */
    public void setMsOpenId(String msOpenId) {
        this.msOpenId = msOpenId;
    }
    /**
     * @param nickName 会中用户名
     */
    public V1MeetingsMeetingIdQosGet200ResponseParticipantsInner nickName(String nickName) {
        this.nickName = nickName;
        return this;
    }
    /**
     * @return nickName 会中用户名
     **/
    public String getNickName() {
        return nickName;
    }

    /**
     * @param nickName 会中用户名
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
    /**
     * @param qosDetails 
     */
    public V1MeetingsMeetingIdQosGet200ResponseParticipantsInner qosDetails(List<V1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInner> qosDetails) {
        this.qosDetails = qosDetails;
        return this;
    }
    /**
     * @return qosDetails 
     **/
    public List<V1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInner> getQosDetails() {
        return qosDetails;
    }

    /**
     * @param qosDetails 
     */
    public void setQosDetails(List<V1MeetingsMeetingIdQosGet200ResponseParticipantsInnerQosDetailsInner> qosDetails) {
        this.qosDetails = qosDetails;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1MeetingsMeetingIdQosGet200ResponseParticipantsInner v1MeetingsMeetingIdQosGet200ResponseParticipantsInner = (V1MeetingsMeetingIdQosGet200ResponseParticipantsInner) o;
        return Objects.equals(this.msOpenId, v1MeetingsMeetingIdQosGet200ResponseParticipantsInner.msOpenId) &&
            Objects.equals(this.nickName, v1MeetingsMeetingIdQosGet200ResponseParticipantsInner.nickName) &&
            Objects.equals(this.qosDetails, v1MeetingsMeetingIdQosGet200ResponseParticipantsInner.qosDetails);
    }

    @Override
    public int hashCode() {
        return Objects.hash(msOpenId, nickName, qosDetails);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1MeetingsMeetingIdQosGet200ResponseParticipantsInner {\n");
        sb.append("    msOpenId: ").append(toIndentedString(msOpenId)).append("\n");
        sb.append("    nickName: ").append(toIndentedString(nickName)).append("\n");
        sb.append("    qosDetails: ").append(toIndentedString(qosDetails)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

