/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.meetings.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * V1MeetingsMeetingIdEnrollApprovalsGet200Response
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1MeetingsMeetingIdEnrollApprovalsGet200Response {
    @JsonProperty(value = "current_page")
    private Long currentPage;

    @JsonProperty(value = "current_size")
    private Long currentSize;

    @JsonProperty(value = "enroll_list")
    private List<V1MeetingsMeetingIdEnrollApprovalsGet200ResponseEnrollListInner> enrollList;

    @JsonProperty(value = "total_count")
    private Long totalCount;

    @JsonProperty(value = "total_page")
    private Long totalPage;

    /**
     */
    public V1MeetingsMeetingIdEnrollApprovalsGet200Response() {
    }

    /**
     * @param currentPage 当前页
     */
    public V1MeetingsMeetingIdEnrollApprovalsGet200Response currentPage(Long currentPage) {
        this.currentPage = currentPage;
        return this;
    }
    /**
     * @return currentPage 当前页
     **/
    public Long getCurrentPage() {
        return currentPage;
    }

    /**
     * @param currentPage 当前页
     */
    public void setCurrentPage(Long currentPage) {
        this.currentPage = currentPage;
    }
    /**
     * @param currentSize 当前页实际大小
     */
    public V1MeetingsMeetingIdEnrollApprovalsGet200Response currentSize(Long currentSize) {
        this.currentSize = currentSize;
        return this;
    }
    /**
     * @return currentSize 当前页实际大小
     **/
    public Long getCurrentSize() {
        return currentSize;
    }

    /**
     * @param currentSize 当前页实际大小
     */
    public void setCurrentSize(Long currentSize) {
        this.currentSize = currentSize;
    }
    /**
     * @param enrollList 当前页的报名列表，current_size为0时无该字段
     */
    public V1MeetingsMeetingIdEnrollApprovalsGet200Response enrollList(List<V1MeetingsMeetingIdEnrollApprovalsGet200ResponseEnrollListInner> enrollList) {
        this.enrollList = enrollList;
        return this;
    }
    /**
     * @return enrollList 当前页的报名列表，current_size为0时无该字段
     **/
    public List<V1MeetingsMeetingIdEnrollApprovalsGet200ResponseEnrollListInner> getEnrollList() {
        return enrollList;
    }

    /**
     * @param enrollList 当前页的报名列表，current_size为0时无该字段
     */
    public void setEnrollList(List<V1MeetingsMeetingIdEnrollApprovalsGet200ResponseEnrollListInner> enrollList) {
        this.enrollList = enrollList;
    }
    /**
     * @param totalCount 根据条件筛选后的总报名人数
     */
    public V1MeetingsMeetingIdEnrollApprovalsGet200Response totalCount(Long totalCount) {
        this.totalCount = totalCount;
        return this;
    }
    /**
     * @return totalCount 根据条件筛选后的总报名人数
     **/
    public Long getTotalCount() {
        return totalCount;
    }

    /**
     * @param totalCount 根据条件筛选后的总报名人数
     */
    public void setTotalCount(Long totalCount) {
        this.totalCount = totalCount;
    }
    /**
     * @param totalPage 根据条件筛选后的总分页数
     */
    public V1MeetingsMeetingIdEnrollApprovalsGet200Response totalPage(Long totalPage) {
        this.totalPage = totalPage;
        return this;
    }
    /**
     * @return totalPage 根据条件筛选后的总分页数
     **/
    public Long getTotalPage() {
        return totalPage;
    }

    /**
     * @param totalPage 根据条件筛选后的总分页数
     */
    public void setTotalPage(Long totalPage) {
        this.totalPage = totalPage;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1MeetingsMeetingIdEnrollApprovalsGet200Response v1MeetingsMeetingIdEnrollApprovalsGet200Response = (V1MeetingsMeetingIdEnrollApprovalsGet200Response) o;
        return Objects.equals(this.currentPage, v1MeetingsMeetingIdEnrollApprovalsGet200Response.currentPage) &&
            Objects.equals(this.currentSize, v1MeetingsMeetingIdEnrollApprovalsGet200Response.currentSize) &&
            Objects.equals(this.enrollList, v1MeetingsMeetingIdEnrollApprovalsGet200Response.enrollList) &&
            Objects.equals(this.totalCount, v1MeetingsMeetingIdEnrollApprovalsGet200Response.totalCount) &&
            Objects.equals(this.totalPage, v1MeetingsMeetingIdEnrollApprovalsGet200Response.totalPage);
    }

    @Override
    public int hashCode() {
        return Objects.hash(currentPage, currentSize, enrollList, totalCount, totalPage);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1MeetingsMeetingIdEnrollApprovalsGet200Response {\n");
        sb.append("    currentPage: ").append(toIndentedString(currentPage)).append("\n");
        sb.append("    currentSize: ").append(toIndentedString(currentSize)).append("\n");
        sb.append("    enrollList: ").append(toIndentedString(enrollList)).append("\n");
        sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
        sb.append("    totalPage: ").append(toIndentedString(totalPage)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

