/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.meeting_room.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * V1DevicesGet200Response
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1DevicesGet200Response {
    @JsonProperty(value = "current_page")
    private Long currentPage;

    @JsonProperty(value = "current_size")
    private Long currentSize;

    @JsonProperty(value = "device_info_list")
    private List<V1DevicesGet200ResponseDeviceInfoListInner> deviceInfoList;

    @JsonProperty(value = "total_count")
    private Long totalCount;

    @JsonProperty(value = "total_page")
    private Long totalPage;

    /**
     */
    public V1DevicesGet200Response() {
    }

    /**
     * @param currentPage 当前页
     */
    public V1DevicesGet200Response currentPage(Long currentPage) {
        this.currentPage = currentPage;
        return this;
    }
    /**
     * @return currentPage 当前页
     **/
    public Long getCurrentPage() {
        return currentPage;
    }

    /**
     * @param currentPage 当前页
     */
    public void setCurrentPage(Long currentPage) {
        this.currentPage = currentPage;
    }
    /**
     * @param currentSize 单页条数
     */
    public V1DevicesGet200Response currentSize(Long currentSize) {
        this.currentSize = currentSize;
        return this;
    }
    /**
     * @return currentSize 单页条数
     **/
    public Long getCurrentSize() {
        return currentSize;
    }

    /**
     * @param currentSize 单页条数
     */
    public void setCurrentSize(Long currentSize) {
        this.currentSize = currentSize;
    }
    /**
     * @param deviceInfoList 设备对象列表
     */
    public V1DevicesGet200Response deviceInfoList(List<V1DevicesGet200ResponseDeviceInfoListInner> deviceInfoList) {
        this.deviceInfoList = deviceInfoList;
        return this;
    }
    /**
     * @return deviceInfoList 设备对象列表
     **/
    public List<V1DevicesGet200ResponseDeviceInfoListInner> getDeviceInfoList() {
        return deviceInfoList;
    }

    /**
     * @param deviceInfoList 设备对象列表
     */
    public void setDeviceInfoList(List<V1DevicesGet200ResponseDeviceInfoListInner> deviceInfoList) {
        this.deviceInfoList = deviceInfoList;
    }
    /**
     * @param totalCount 数据总条数
     */
    public V1DevicesGet200Response totalCount(Long totalCount) {
        this.totalCount = totalCount;
        return this;
    }
    /**
     * @return totalCount 数据总条数
     **/
    public Long getTotalCount() {
        return totalCount;
    }

    /**
     * @param totalCount 数据总条数
     */
    public void setTotalCount(Long totalCount) {
        this.totalCount = totalCount;
    }
    /**
     * @param totalPage 数据总页数
     */
    public V1DevicesGet200Response totalPage(Long totalPage) {
        this.totalPage = totalPage;
        return this;
    }
    /**
     * @return totalPage 数据总页数
     **/
    public Long getTotalPage() {
        return totalPage;
    }

    /**
     * @param totalPage 数据总页数
     */
    public void setTotalPage(Long totalPage) {
        this.totalPage = totalPage;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1DevicesGet200Response v1DevicesGet200Response = (V1DevicesGet200Response) o;
        return Objects.equals(this.currentPage, v1DevicesGet200Response.currentPage) &&
            Objects.equals(this.currentSize, v1DevicesGet200Response.currentSize) &&
            Objects.equals(this.deviceInfoList, v1DevicesGet200Response.deviceInfoList) &&
            Objects.equals(this.totalCount, v1DevicesGet200Response.totalCount) &&
            Objects.equals(this.totalPage, v1DevicesGet200Response.totalPage);
    }

    @Override
    public int hashCode() {
        return Objects.hash(currentPage, currentSize, deviceInfoList, totalCount, totalPage);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1DevicesGet200Response {\n");
        sb.append("    currentPage: ").append(toIndentedString(currentPage)).append("\n");
        sb.append("    currentSize: ").append(toIndentedString(currentSize)).append("\n");
        sb.append("    deviceInfoList: ").append(toIndentedString(deviceInfoList)).append("\n");
        sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
        sb.append("    totalPage: ").append(toIndentedString(totalPage)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

