/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.meeting_room.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * V1MeetingRoomsRoomCallPut200Response
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1MeetingRoomsRoomCallPut200Response {
    @JsonProperty(value = "invite_id")
    private String inviteId;

    @JsonProperty(value = "status")
    private Long status;

    /**
     */
    public V1MeetingRoomsRoomCallPut200Response() {
    }

    /**
     * @param inviteId 呼叫ID
     */
    public V1MeetingRoomsRoomCallPut200Response inviteId(String inviteId) {
        this.inviteId = inviteId;
        return this;
    }
    /**
     * @return inviteId 呼叫ID
     **/
    public String getInviteId() {
        return inviteId;
    }

    /**
     * @param inviteId 呼叫ID
     */
    public void setInviteId(String inviteId) {
        this.inviteId = inviteId;
    }
    /**
     * @param status 
     */
    public V1MeetingRoomsRoomCallPut200Response status(Long status) {
        this.status = status;
        return this;
    }
    /**
     * @return status 
     **/
    public Long getStatus() {
        return status;
    }

    /**
     * @param status 
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1MeetingRoomsRoomCallPut200Response v1MeetingRoomsRoomCallPut200Response = (V1MeetingRoomsRoomCallPut200Response) o;
        return Objects.equals(this.inviteId, v1MeetingRoomsRoomCallPut200Response.inviteId) &&
            Objects.equals(this.status, v1MeetingRoomsRoomCallPut200Response.status);
    }

    @Override
    public int hashCode() {
        return Objects.hash(inviteId, status);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1MeetingRoomsRoomCallPut200Response {\n");
        sb.append("    inviteId: ").append(toIndentedString(inviteId)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

