/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.meeting_room.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * V1MeetingsMeetingIdBookRoomsPost200ResponseMeetingRoomListInner
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1MeetingsMeetingIdBookRoomsPost200ResponseMeetingRoomListInner {
    @JsonProperty(value = "meeting_room_id")
    private String meetingRoomId;

    @JsonProperty(value = "meeting_room_location")
    private String meetingRoomLocation;

    @JsonProperty(value = "meeting_room_name")
    private String meetingRoomName;

    /**
     */
    public V1MeetingsMeetingIdBookRoomsPost200ResponseMeetingRoomListInner() {
    }

    /**
     * @param meetingRoomId 会议室ID
     */
    public V1MeetingsMeetingIdBookRoomsPost200ResponseMeetingRoomListInner meetingRoomId(String meetingRoomId) {
        this.meetingRoomId = meetingRoomId;
        return this;
    }
    /**
     * @return meetingRoomId 会议室ID
     **/
    public String getMeetingRoomId() {
        return meetingRoomId;
    }

    /**
     * @param meetingRoomId 会议室ID
     */
    public void setMeetingRoomId(String meetingRoomId) {
        this.meetingRoomId = meetingRoomId;
    }
    /**
     * @param meetingRoomLocation 会议室地址
     */
    public V1MeetingsMeetingIdBookRoomsPost200ResponseMeetingRoomListInner meetingRoomLocation(String meetingRoomLocation) {
        this.meetingRoomLocation = meetingRoomLocation;
        return this;
    }
    /**
     * @return meetingRoomLocation 会议室地址
     **/
    public String getMeetingRoomLocation() {
        return meetingRoomLocation;
    }

    /**
     * @param meetingRoomLocation 会议室地址
     */
    public void setMeetingRoomLocation(String meetingRoomLocation) {
        this.meetingRoomLocation = meetingRoomLocation;
    }
    /**
     * @param meetingRoomName 会议室名称
     */
    public V1MeetingsMeetingIdBookRoomsPost200ResponseMeetingRoomListInner meetingRoomName(String meetingRoomName) {
        this.meetingRoomName = meetingRoomName;
        return this;
    }
    /**
     * @return meetingRoomName 会议室名称
     **/
    public String getMeetingRoomName() {
        return meetingRoomName;
    }

    /**
     * @param meetingRoomName 会议室名称
     */
    public void setMeetingRoomName(String meetingRoomName) {
        this.meetingRoomName = meetingRoomName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1MeetingsMeetingIdBookRoomsPost200ResponseMeetingRoomListInner v1MeetingsMeetingIdBookRoomsPost200ResponseMeetingRoomListInner = (V1MeetingsMeetingIdBookRoomsPost200ResponseMeetingRoomListInner) o;
        return Objects.equals(this.meetingRoomId, v1MeetingsMeetingIdBookRoomsPost200ResponseMeetingRoomListInner.meetingRoomId) &&
            Objects.equals(this.meetingRoomLocation, v1MeetingsMeetingIdBookRoomsPost200ResponseMeetingRoomListInner.meetingRoomLocation) &&
            Objects.equals(this.meetingRoomName, v1MeetingsMeetingIdBookRoomsPost200ResponseMeetingRoomListInner.meetingRoomName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(meetingRoomId, meetingRoomLocation, meetingRoomName);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1MeetingsMeetingIdBookRoomsPost200ResponseMeetingRoomListInner {\n");
        sb.append("    meetingRoomId: ").append(toIndentedString(meetingRoomId)).append("\n");
        sb.append("    meetingRoomLocation: ").append(toIndentedString(meetingRoomLocation)).append("\n");
        sb.append("    meetingRoomName: ").append(toIndentedString(meetingRoomName)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

