/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.meeting_room.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * 会议室会议配置对象
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettings {
    @JsonProperty(value = "auto_response")
    private Long autoResponse;

    @JsonProperty(value = "caption")
    private Boolean caption;

    @JsonProperty(value = "room_notification")
    private Boolean roomNotification;

    @JsonProperty(value = "room_pmi")
    private Boolean roomPmi;

    @JsonProperty(value = "room_pmi_settings")
    private V1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettingsRoomPmiSettings roomPmiSettings;

    @JsonProperty(value = "water_mark")
    private Long waterMark;

    /**
     */
    public V1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettings() {
    }

    /**
     * @param autoResponse 自动接听。 1：开启 2：关闭
     */
    public V1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettings autoResponse(Long autoResponse) {
        this.autoResponse = autoResponse;
        return this;
    }
    /**
     * @return autoResponse 自动接听。 1：开启 2：关闭
     **/
    public Long getAutoResponse() {
        return autoResponse;
    }

    /**
     * @param autoResponse 自动接听。 1：开启 2：关闭
     */
    public void setAutoResponse(Long autoResponse) {
        this.autoResponse = autoResponse;
    }
    /**
     * @param caption 字幕。 true：开启 false：关闭
     */
    public V1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettings caption(Boolean caption) {
        this.caption = caption;
        return this;
    }
    /**
     * @return caption 字幕。 true：开启 false：关闭
     **/
    public Boolean getCaption() {
        return caption;
    }

    /**
     * @param caption 字幕。 true：开启 false：关闭
     */
    public void setCaption(Boolean caption) {
        this.caption = caption;
    }
    /**
     * @param roomNotification Rooms 屏幕是否展示消息通知。 true：开启 false：不开启
     */
    public V1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettings roomNotification(Boolean roomNotification) {
        this.roomNotification = roomNotification;
        return this;
    }
    /**
     * @return roomNotification Rooms 屏幕是否展示消息通知。 true：开启 false：不开启
     **/
    public Boolean getRoomNotification() {
        return roomNotification;
    }

    /**
     * @param roomNotification Rooms 屏幕是否展示消息通知。 true：开启 false：不开启
     */
    public void setRoomNotification(Boolean roomNotification) {
        this.roomNotification = roomNotification;
    }
    /**
     * @param roomPmi 专属 ID。 true：开启 false：关闭
     */
    public V1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettings roomPmi(Boolean roomPmi) {
        this.roomPmi = roomPmi;
        return this;
    }
    /**
     * @return roomPmi 专属 ID。 true：开启 false：关闭
     **/
    public Boolean getRoomPmi() {
        return roomPmi;
    }

    /**
     * @param roomPmi 专属 ID。 true：开启 false：关闭
     */
    public void setRoomPmi(Boolean roomPmi) {
        this.roomPmi = roomPmi;
    }
    /**
     * @param roomPmiSettings 
     */
    public V1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettings roomPmiSettings(V1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettingsRoomPmiSettings roomPmiSettings) {
        this.roomPmiSettings = roomPmiSettings;
        return this;
    }
    /**
     * @return roomPmiSettings 
     **/
    public V1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettingsRoomPmiSettings getRoomPmiSettings() {
        return roomPmiSettings;
    }

    /**
     * @param roomPmiSettings 
     */
    public void setRoomPmiSettings(V1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettingsRoomPmiSettings roomPmiSettings) {
        this.roomPmiSettings = roomPmiSettings;
    }
    /**
     * @param waterMark 水印。 0：关闭 1：单排水印 2：多排水印
     */
    public V1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettings waterMark(Long waterMark) {
        this.waterMark = waterMark;
        return this;
    }
    /**
     * @return waterMark 水印。 0：关闭 1：单排水印 2：多排水印
     **/
    public Long getWaterMark() {
        return waterMark;
    }

    /**
     * @param waterMark 水印。 0：关闭 1：单排水印 2：多排水印
     */
    public void setWaterMark(Long waterMark) {
        this.waterMark = waterMark;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettings v1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettings = (V1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettings) o;
        return Objects.equals(this.autoResponse, v1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettings.autoResponse) &&
            Objects.equals(this.caption, v1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettings.caption) &&
            Objects.equals(this.roomNotification, v1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettings.roomNotification) &&
            Objects.equals(this.roomPmi, v1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettings.roomPmi) &&
            Objects.equals(this.roomPmiSettings, v1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettings.roomPmiSettings) &&
            Objects.equals(this.waterMark, v1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettings.waterMark);
    }

    @Override
    public int hashCode() {
        return Objects.hash(autoResponse, caption, roomNotification, roomPmi, roomPmiSettings, waterMark);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1MeetingRoomsRoomConfigInfoPost200ResponseMeetingSettings {\n");
        sb.append("    autoResponse: ").append(toIndentedString(autoResponse)).append("\n");
        sb.append("    caption: ").append(toIndentedString(caption)).append("\n");
        sb.append("    roomNotification: ").append(toIndentedString(roomNotification)).append("\n");
        sb.append("    roomPmi: ").append(toIndentedString(roomPmi)).append("\n");
        sb.append("    roomPmiSettings: ").append(toIndentedString(roomPmiSettings)).append("\n");
        sb.append("    waterMark: ").append(toIndentedString(waterMark)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

