/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.meeting_room.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * 会议室 PMI 信息
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1MeetingRoomsMeetingRoomIdGet200ResponsePmiInfo {
    @JsonProperty(value = "pmi_code")
    private String pmiCode;

    @JsonProperty(value = "pmi_pwd")
    private String pmiPwd;

    /**
     */
    public V1MeetingRoomsMeetingRoomIdGet200ResponsePmiInfo() {
    }

    /**
     * @param pmiCode 设备会议号
     */
    public V1MeetingRoomsMeetingRoomIdGet200ResponsePmiInfo pmiCode(String pmiCode) {
        this.pmiCode = pmiCode;
        return this;
    }
    /**
     * @return pmiCode 设备会议号
     **/
    public String getPmiCode() {
        return pmiCode;
    }

    /**
     * @param pmiCode 设备会议号
     */
    public void setPmiCode(String pmiCode) {
        this.pmiCode = pmiCode;
    }
    /**
     * @param pmiPwd 设备入会密码
     */
    public V1MeetingRoomsMeetingRoomIdGet200ResponsePmiInfo pmiPwd(String pmiPwd) {
        this.pmiPwd = pmiPwd;
        return this;
    }
    /**
     * @return pmiPwd 设备入会密码
     **/
    public String getPmiPwd() {
        return pmiPwd;
    }

    /**
     * @param pmiPwd 设备入会密码
     */
    public void setPmiPwd(String pmiPwd) {
        this.pmiPwd = pmiPwd;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1MeetingRoomsMeetingRoomIdGet200ResponsePmiInfo v1MeetingRoomsMeetingRoomIdGet200ResponsePmiInfo = (V1MeetingRoomsMeetingRoomIdGet200ResponsePmiInfo) o;
        return Objects.equals(this.pmiCode, v1MeetingRoomsMeetingRoomIdGet200ResponsePmiInfo.pmiCode) &&
            Objects.equals(this.pmiPwd, v1MeetingRoomsMeetingRoomIdGet200ResponsePmiInfo.pmiPwd);
    }

    @Override
    public int hashCode() {
        return Objects.hash(pmiCode, pmiPwd);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1MeetingRoomsMeetingRoomIdGet200ResponsePmiInfo {\n");
        sb.append("    pmiCode: ").append(toIndentedString(pmiCode)).append("\n");
        sb.append("    pmiPwd: ").append(toIndentedString(pmiPwd)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

