/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.meeting_room.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * V1MeetingRoomsScreencastCodeRoomsInfoGet200Response
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1MeetingRoomsScreencastCodeRoomsInfoGet200Response {
    @JsonProperty(value = "api_password")
    private String apiPassword;

    @JsonProperty(value = "cs_api_enable")
    private Boolean csApiEnable;

    @JsonProperty(value = "meeting_room_id")
    private String meetingRoomId;

    @JsonProperty(value = "rooms_id")
    private String roomsId;

    @JsonProperty(value = "rooms_ip_list")
    private List<String> roomsIpList;

    /**
     */
    public V1MeetingRoomsScreencastCodeRoomsInfoGet200Response() {
    }

    /**
     * @param apiPassword 中控API密码
     */
    public V1MeetingRoomsScreencastCodeRoomsInfoGet200Response apiPassword(String apiPassword) {
        this.apiPassword = apiPassword;
        return this;
    }
    /**
     * @return apiPassword 中控API密码
     **/
    public String getApiPassword() {
        return apiPassword;
    }

    /**
     * @param apiPassword 中控API密码
     */
    public void setApiPassword(String apiPassword) {
        this.apiPassword = apiPassword;
    }
    /**
     * @param csApiEnable 中控API开关
     */
    public V1MeetingRoomsScreencastCodeRoomsInfoGet200Response csApiEnable(Boolean csApiEnable) {
        this.csApiEnable = csApiEnable;
        return this;
    }
    /**
     * @return csApiEnable 中控API开关
     **/
    public Boolean getCsApiEnable() {
        return csApiEnable;
    }

    /**
     * @param csApiEnable 中控API开关
     */
    public void setCsApiEnable(Boolean csApiEnable) {
        this.csApiEnable = csApiEnable;
    }
    /**
     * @param meetingRoomId 会议室ID
     */
    public V1MeetingRoomsScreencastCodeRoomsInfoGet200Response meetingRoomId(String meetingRoomId) {
        this.meetingRoomId = meetingRoomId;
        return this;
    }
    /**
     * @return meetingRoomId 会议室ID
     **/
    public String getMeetingRoomId() {
        return meetingRoomId;
    }

    /**
     * @param meetingRoomId 会议室ID
     */
    public void setMeetingRoomId(String meetingRoomId) {
        this.meetingRoomId = meetingRoomId;
    }
    /**
     * @param roomsId Rooms ID
     */
    public V1MeetingRoomsScreencastCodeRoomsInfoGet200Response roomsId(String roomsId) {
        this.roomsId = roomsId;
        return this;
    }
    /**
     * @return roomsId Rooms ID
     **/
    public String getRoomsId() {
        return roomsId;
    }

    /**
     * @param roomsId Rooms ID
     */
    public void setRoomsId(String roomsId) {
        this.roomsId = roomsId;
    }
    /**
     * @param roomsIpList rooms的IP列表
     */
    public V1MeetingRoomsScreencastCodeRoomsInfoGet200Response roomsIpList(List<String> roomsIpList) {
        this.roomsIpList = roomsIpList;
        return this;
    }
    /**
     * @return roomsIpList rooms的IP列表
     **/
    public List<String> getRoomsIpList() {
        return roomsIpList;
    }

    /**
     * @param roomsIpList rooms的IP列表
     */
    public void setRoomsIpList(List<String> roomsIpList) {
        this.roomsIpList = roomsIpList;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1MeetingRoomsScreencastCodeRoomsInfoGet200Response v1MeetingRoomsScreencastCodeRoomsInfoGet200Response = (V1MeetingRoomsScreencastCodeRoomsInfoGet200Response) o;
        return Objects.equals(this.apiPassword, v1MeetingRoomsScreencastCodeRoomsInfoGet200Response.apiPassword) &&
            Objects.equals(this.csApiEnable, v1MeetingRoomsScreencastCodeRoomsInfoGet200Response.csApiEnable) &&
            Objects.equals(this.meetingRoomId, v1MeetingRoomsScreencastCodeRoomsInfoGet200Response.meetingRoomId) &&
            Objects.equals(this.roomsId, v1MeetingRoomsScreencastCodeRoomsInfoGet200Response.roomsId) &&
            Objects.equals(this.roomsIpList, v1MeetingRoomsScreencastCodeRoomsInfoGet200Response.roomsIpList);
    }

    @Override
    public int hashCode() {
        return Objects.hash(apiPassword, csApiEnable, meetingRoomId, roomsId, roomsIpList);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1MeetingRoomsScreencastCodeRoomsInfoGet200Response {\n");
        sb.append("    apiPassword: ").append(toIndentedString(apiPassword)).append("\n");
        sb.append("    csApiEnable: ").append(toIndentedString(csApiEnable)).append("\n");
        sb.append("    meetingRoomId: ").append(toIndentedString(meetingRoomId)).append("\n");
        sb.append("    roomsId: ").append(toIndentedString(roomsId)).append("\n");
        sb.append("    roomsIpList: ").append(toIndentedString(roomsIpList)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

