/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.user_manager.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * V1UsersAdvanceListGet200ResponseUsersInnerDepartmentListInner
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1UsersAdvanceListGet200ResponseUsersInnerDepartmentListInner {
    @JsonProperty(value = "department_full_name")
    private String departmentFullName;

    @JsonProperty(value = "department_id")
    private String departmentId;

    @JsonProperty(value = "department_name")
    private String departmentName;

    @JsonProperty(value = "is_main")
    private Boolean isMain;

    /**
     */
    public V1UsersAdvanceListGet200ResponseUsersInnerDepartmentListInner() {
    }

    /**
     * @param departmentFullName 部门全路径
     */
    public V1UsersAdvanceListGet200ResponseUsersInnerDepartmentListInner departmentFullName(String departmentFullName) {
        this.departmentFullName = departmentFullName;
        return this;
    }
    /**
     * @return departmentFullName 部门全路径
     **/
    public String getDepartmentFullName() {
        return departmentFullName;
    }

    /**
     * @param departmentFullName 部门全路径
     */
    public void setDepartmentFullName(String departmentFullName) {
        this.departmentFullName = departmentFullName;
    }
    /**
     * @param departmentId 部门ID
     */
    public V1UsersAdvanceListGet200ResponseUsersInnerDepartmentListInner departmentId(String departmentId) {
        this.departmentId = departmentId;
        return this;
    }
    /**
     * @return departmentId 部门ID
     **/
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * @param departmentId 部门ID
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }
    /**
     * @param departmentName 部门名称
     */
    public V1UsersAdvanceListGet200ResponseUsersInnerDepartmentListInner departmentName(String departmentName) {
        this.departmentName = departmentName;
        return this;
    }
    /**
     * @return departmentName 部门名称
     **/
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * @param departmentName 部门名称
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
    /**
     * @param isMain 是否主部门
     */
    public V1UsersAdvanceListGet200ResponseUsersInnerDepartmentListInner isMain(Boolean isMain) {
        this.isMain = isMain;
        return this;
    }
    /**
     * @return isMain 是否主部门
     **/
    public Boolean getIsMain() {
        return isMain;
    }

    /**
     * @param isMain 是否主部门
     */
    public void setIsMain(Boolean isMain) {
        this.isMain = isMain;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1UsersAdvanceListGet200ResponseUsersInnerDepartmentListInner v1UsersAdvanceListGet200ResponseUsersInnerDepartmentListInner = (V1UsersAdvanceListGet200ResponseUsersInnerDepartmentListInner) o;
        return Objects.equals(this.departmentFullName, v1UsersAdvanceListGet200ResponseUsersInnerDepartmentListInner.departmentFullName) &&
            Objects.equals(this.departmentId, v1UsersAdvanceListGet200ResponseUsersInnerDepartmentListInner.departmentId) &&
            Objects.equals(this.departmentName, v1UsersAdvanceListGet200ResponseUsersInnerDepartmentListInner.departmentName) &&
            Objects.equals(this.isMain, v1UsersAdvanceListGet200ResponseUsersInnerDepartmentListInner.isMain);
    }

    @Override
    public int hashCode() {
        return Objects.hash(departmentFullName, departmentId, departmentName, isMain);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1UsersAdvanceListGet200ResponseUsersInnerDepartmentListInner {\n");
        sb.append("    departmentFullName: ").append(toIndentedString(departmentFullName)).append("\n");
        sb.append("    departmentId: ").append(toIndentedString(departmentId)).append("\n");
        sb.append("    departmentName: ").append(toIndentedString(departmentName)).append("\n");
        sb.append("    isMain: ").append(toIndentedString(isMain)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

