/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.user_manager.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * V1UsersInviteActivatePost200ResponseInactivateUserListInner
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1UsersInviteActivatePost200ResponseInactivateUserListInner {
    @JsonProperty(value = "activate_url")
    private String activateUrl;

    @JsonProperty(value = "userid")
    private String userid;

    /**
     */
    public V1UsersInviteActivatePost200ResponseInactivateUserListInner() {
    }

    /**
     * @param activateUrl 激活链接
     */
    public V1UsersInviteActivatePost200ResponseInactivateUserListInner activateUrl(String activateUrl) {
        this.activateUrl = activateUrl;
        return this;
    }
    /**
     * @return activateUrl 激活链接
     **/
    public String getActivateUrl() {
        return activateUrl;
    }

    /**
     * @param activateUrl 激活链接
     */
    public void setActivateUrl(String activateUrl) {
        this.activateUrl = activateUrl;
    }
    /**
     * @param userid 
     */
    public V1UsersInviteActivatePost200ResponseInactivateUserListInner userid(String userid) {
        this.userid = userid;
        return this;
    }
    /**
     * @return userid 
     **/
    public String getUserid() {
        return userid;
    }

    /**
     * @param userid 
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1UsersInviteActivatePost200ResponseInactivateUserListInner v1UsersInviteActivatePost200ResponseInactivateUserListInner = (V1UsersInviteActivatePost200ResponseInactivateUserListInner) o;
        return Objects.equals(this.activateUrl, v1UsersInviteActivatePost200ResponseInactivateUserListInner.activateUrl) &&
            Objects.equals(this.userid, v1UsersInviteActivatePost200ResponseInactivateUserListInner.userid);
    }

    @Override
    public int hashCode() {
        return Objects.hash(activateUrl, userid);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1UsersInviteActivatePost200ResponseInactivateUserListInner {\n");
        sb.append("    activateUrl: ").append(toIndentedString(activateUrl)).append("\n");
        sb.append("    userid: ").append(toIndentedString(userid)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

